{{- define "common.virtual-service" -}}

{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "common.fullname" .}}-virtual
spec:
  hosts:
    - {{ include "common.fullname" .}}
  http:
    - route:
        - destination:
            host: {{ include "common.fullname" .}}
      timeout: 20s
      retries:
        attempts: 3
        retryOn: 5xx
        perTryTimeout: 20s
{{ end }}
{{- end -}}