apiVersion: apps/v1
kind: Deployment                             # Deployment - це конфігурація Kubernetes, що дозволяє описувати бажаний стан системи і являє собою набір з декількох однакових Pod без унікальних ідентифікаційних даних.Також в Deployments можна задаати стратегії оновлення подів 
metadata:
  name: webui-deployment
spec:
  replicas: 2                                # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: webui                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
     labels:
       app: webui               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: denysl1enk0/mslabsngclient:0.1
          name: webui           # ім'я контейнеру
          ports:
            - containerPort: 80              # порт по якому можна звертатись до поди
