apiVersion: v1
kind: Service            # це абстракція, що об'єднує логічний набір Pod і забезпечує доступ до них. Набір Pod, призначених для Service, зазвичай визначається через selector.
metadata:
  name: webui-svc
spec:
  ports:
    - port: 80           # порт по якому можна звератись до сервісу
      targetPort: 80     # порт контейнера
  selector:
    app: webui           # селектор, всі Pod з даним селектором, будуть підключені до даного сервісу
  type: NodePort