kubectl apply -f ../k8s/employee-service/
kubectl apply -f ../k8s/employee-service/db
kubectl apply -f ../k8s/item-service/
kubectl apply -f ../k8s/item-service/db
kubectl apply -f ../k8s/storage-service/
kubectl apply -f ../k8s/storage-service/db
kubectl apply -f ../k8s/transaction-service/
kubectl apply -f ../k8s/transaction-service/db
kubectl apply -f ../k8s/client/