kubectl delete -f ../k8s/employee-service/
kubectl delete -f ../k8s/employee-service/db
kubectl delete -f ../k8s/item-service/
kubectl delete -f ../k8s/item-service/db
kubectl delete -f ../k8s/storage-service/
kubectl delete -f ../k8s/storage-service/db
kubectl delete -f ../k8s/transaction-service/
kubectl delete -f ../k8s/transaction-service/db
kubectl delete -f ../k8s/client/