replicasCount: 1

image: 
  name: zozuliuk22/storageservice
  tag: 0.1

containers:
  name: storageservice
  containerPort: 80

service:
  ports:
    - name: http
      port: 8080
      targetPort: 80

ingress:
  path: /api/storageservice(/|$)(.*)
  pathType: Prefix
  port:
    number: 8080
  
secrets:
  SA_PASSWORD: "UGE1NXcwcmQh"

storage-service-mssql:
  config:
    saPassword: "Pa55w0rd!"
    