apiVersion: apps/v1
kind: Deployment                            
metadata:
  name: {{ include "common.fullname" .}}
spec:
  replicas: {{ .Values.replicasCount | default 1 }}                       
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}               
  template:
    metadata:
     labels:
       {{- include "common.selectorLabels" . | nindent 8 }}             
    spec:
      containers:
        - image:  {{ .Values.image.name }}:{{ .Values.image.tag }}
          name: {{ .Values.containers.name }}      
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
