apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employeeservice-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /employeeservice(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: employeeservice-svc
            port: 
              number: 8080