apiVersion: apps/v1
kind: Deployment                             # Deployment - це конфігурація Kubernetes, що дозволяє описувати бажаний стан системи і являє собою набір з декількох однакових Pod без унікальних ідентифікаційних даних.Також в Deployments можна задаати стратегії оновлення подів 
metadata:
  name: itemservice-deployment
spec:
  replicas: 1                               # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: itemservice                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
     labels:
       app: itemservice               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: vynnykv/item-service:latest
          name: itemservice           # ім'я контейнеру
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
          ports:
            - containerPort: 80              # порт по якому можна звертатись до поди
