apiVersion: v1
kind: Service         
metadata:
  name: storage-app-storage-service-mssql
spec:
  selector:
    app: storage-db  
  ports:
    - protocol: TCP
      port: 1433             
      targetPort: 1433      
  type: ClusterIP