// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageService.Data;

#nullable disable

namespace StorageService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221030164220_InitialModels")]
    partial class InitialModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StorageService.Models.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03dec121-ac0e-4189-bd9e-68013cd175f1"),
                            Address = "Winners avenue, 10",
                            Name = "Storage A"
                        },
                        new
                        {
                            Id = new Guid("7c164a1e-84ab-44b9-9542-9c0a681172a6"),
                            Address = "Magic street, 70/2",
                            Name = "Storage B"
                        },
                        new
                        {
                            Id = new Guid("8f515945-5f20-4acb-95fc-b0aa2eb91490"),
                            Address = "Central square",
                            Name = "Storage C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
